# This file was generated by GoReleaser. DO NOT EDIT.
cask "holodeck" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "b6992fc3e3ea0d82975565e2ced91d42f759fe7964f522e03678d74b1dd8c24b"
      url "https://github.com/NVIDIA/holodeck/releases/download/v#{version}/holodeck_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e69648541249ec894d1607b1235b029eebab69bc10e8c06914528e08414ad74f"
      url "https://github.com/NVIDIA/holodeck/releases/download/v#{version}/holodeck_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "holodeck"
  desc "Tool for creating and managing GPU-ready cloud test environments"
  homepage "https://github.com/NVIDIA/holodeck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "holodeck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/holodeck"],
                     sudo: false
    end
  end

  # No zap stanza required
end
