# This file was generated by GoReleaser. DO NOT EDIT.
cask "holodeck" do
  version "0.3.6"

  on_macos do
    on_intel do
      sha256 "7e4ab6f83b25c0f565f30f8af4cc9bbe5e242934bd2e376dfda3a21db860828e"
      url "https://github.com/NVIDIA/holodeck/releases/download/v#{version}/holodeck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1cda6f824525fe018240445d664c62c69ebff8c3101720684e00aae281f6341"
      url "https://github.com/NVIDIA/holodeck/releases/download/v#{version}/holodeck_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "holodeck"
  desc "Tool for creating and managing GPU-ready cloud test environments"
  homepage "https://github.com/NVIDIA/holodeck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "holodeck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/holodeck"],
                     sudo: false
    end
  end

  # No zap stanza required

end
