apiVersion: holodeck.nvidia.com/v1alpha1
kind: Environment
metadata:
  name: nct-git-tag
spec:
  provider: ssh
  auth:
    keyName: my-key
    username: ubuntu
    publicKey: /path/to/public.key
    privateKey: /path/to/private.key
  instance:
    hostUrl: "my-host.example.com"
  containerRuntime:
    install: true
    name: containerd
  nvidiaContainerToolkit:
    install: true
    enableCDI: true
    source: git
    git:
      repo: https://github.com/NVIDIA/nvidia-container-toolkit.git
      ref: refs/tags/v1.17.6
      build:
        makeTargets: ["all"]
        extraEnv:
          GOFLAGS: "-buildvcs=true"