apiVersion: holodeck.nvidia.com/v1alpha1
kind: Environment
metadata:
  name: nct-latest-main
spec:
  provider: ssh
  auth:
    keyName: my-key
    username: ubuntu
    publicKey: /path/to/public.key
    privateKey: /path/to/private.key
  instance:
    hostUrl: "my-host.example.com"
  containerRuntime:
    install: true
    name: containerd
  nvidiaContainerToolkit:
    install: true
    enableCDI: true
    source: latest
    latest:
      track: main
      # repo defaults to https://github.com/NVIDIA/nvidia-container-toolkit.git