# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Holodeck < Formula
  desc "Tool for creating and managing GPU-ready cloud test environments"
  homepage "https://github.com/NVIDIA/holodeck"
  version "0.4.0"
  license "Apache-2.0"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/NVIDIA/holodeck/releases/download/v0.4.0/holodeck_0.4.0_linux_amd64.tar.gz"
    sha256 "8996af6baca05f3b6a738ac1b94832fd1bf2eb92c8ac4197e9e783f488bc0de5"
    define_method(:install) do
      bin.install "holodeck"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/NVIDIA/holodeck/releases/download/v0.4.0/holodeck_0.4.0_linux_arm64.tar.gz"
    sha256 "73252e2462684bc7f77a8f2b67716f1dea8639f9a242bbdc68a864d86016b666"
    define_method(:install) do
      bin.install "holodeck"
    end
  end

  test do
    system "#{bin}/holodeck", "--version"
  end
end
