# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Holodeck < Formula
  desc "Tool for creating and managing GPU-ready cloud test environments"
  homepage "https://github.com/NVIDIA/holodeck"
  version "0.3.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NVIDIA/holodeck/releases/download/v0.3.5/holodeck_0.3.5_darwin_amd64.tar.gz"
      sha256 "321b33ee0745a8ec662c8f8c99ecb8d8282a99042ceb5e33774d137370d4172d"

      define_method(:install) do
        bin.install "holodeck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NVIDIA/holodeck/releases/download/v0.3.5/holodeck_0.3.5_darwin_arm64.tar.gz"
      sha256 "dd183ce55af427293d4268f82f877c06df6d661a7278176b59ac0bf7197cdbed"

      define_method(:install) do
        bin.install "holodeck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/holodeck/releases/download/v0.3.5/holodeck_0.3.5_linux_amd64.tar.gz"
      sha256 "36f496222b7b0f8c337dc48d6cd19f0fe6e4f1eaf08f28f6843863233ef937b6"
      define_method(:install) do
        bin.install "holodeck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/holodeck/releases/download/v0.3.5/holodeck_0.3.5_linux_arm64.tar.gz"
      sha256 "a22ad3aa61c4d3b7d2aa9e765c659bb74b31fd1704663619ba5b12c451650207"
      define_method(:install) do
        bin.install "holodeck"
      end
    end
  end

  test do
    system "#{bin}/holodeck", "--version"
  end
end
