apiVersion: holodeck.nvidia.com/v1alpha1
kind: Environment
metadata:
  name: draKind
  description: "DRA on Kind infra environment"
spec:
  provider: aws
  auth:
    keyName: HOLODECK_AWS_ACCESS_KEY_ID
    privateKey: HOLODECK_AWS_SECRET_ACCESS_KEY
  instance:
    type: g4dn.xlarge
    region: eu-north-1
    # ingressIpRanges is now optional - your IP is detected automatically
    # ingressIpRanges:
    #   - "YOUR_IP/32"  # Only needed for additional IP ranges
    image:
      architecture: amd64
  kubernetes:
    install: true
    installer: kind
    kindConfig: "./examples/kind.yaml"
