/*
 * Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package templates

import (
	"fmt"
	"regexp"

	"github.com/NVIDIA/holodeck/api/holodeck/v1alpha1"
)

var (
	// versionPattern matches safe version strings (e.g., "v1.31.0", "5.15.0-1057-aws", "1.17.3-1", "550").
	// Rejects shell metacharacters that could lead to command injection.
	versionPattern = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9.\-+~]*$`)

	// gitURLPattern matches safe git repository URLs.
	gitURLPattern = regexp.MustCompile(`^https?://[a-zA-Z0-9][a-zA-Z0-9.\-/:@]*$`)

	// filePathPattern matches safe file system paths.
	// Only allows alphanumeric chars, slashes, dots, underscores, hyphens, and tildes.
	filePathPattern = regexp.MustCompile(`^[a-zA-Z0-9/._\-~]+$`)

	// gitRefPattern matches safe git references (branches, tags, SHAs, PR refs).
	// Allows "/" for refs like "refs/tags/v1.31.0" or "refs/pull/123/head".
	gitRefPattern = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9.\-+~/]*$`)
)

// ValidateTemplateInputs validates user-supplied fields that will be interpolated
// into shell scripts generated by the provisioner templates. This prevents command
// injection via shell metacharacters in version strings, git URLs, and file paths.
func ValidateTemplateInputs(env v1alpha1.Environment) error {
	// Validate version strings
	versions := map[string]string{
		"nvidia driver version":            env.Spec.NVIDIADriver.Version,
		"nvidia driver branch":             env.Spec.NVIDIADriver.Branch,
		"container runtime version":        env.Spec.ContainerRuntime.Version,
		"nvidia container toolkit version": env.Spec.NVIDIAContainerToolkit.Version,
		"kubernetes version":               env.Spec.Kubernetes.KubernetesVersion,
		"calico version":                   env.Spec.Kubernetes.CalicoVersion,
		"cni plugins version":              env.Spec.Kubernetes.CniPluginsVersion,
		"crictl version":                   env.Spec.Kubernetes.CrictlVersion,
		"kubelet release version":          env.Spec.Kubernetes.KubeletReleaseVersion,
		"kernel version":                   env.Spec.Kernel.Version,
	}

	for name, value := range versions {
		if value != "" && !versionPattern.MatchString(value) {
			return fmt.Errorf("invalid %s: %q contains disallowed characters", name, value)
		}
	}

	// Validate release version if set
	if env.Spec.Kubernetes.Release != nil && env.Spec.Kubernetes.Release.Version != "" {
		if !versionPattern.MatchString(env.Spec.Kubernetes.Release.Version) {
			return fmt.Errorf("invalid kubernetes release version: %q contains disallowed characters", env.Spec.Kubernetes.Release.Version)
		}
	}

	// Validate CTK package version if set
	if env.Spec.NVIDIAContainerToolkit.Package != nil && env.Spec.NVIDIAContainerToolkit.Package.Version != "" {
		if !versionPattern.MatchString(env.Spec.NVIDIAContainerToolkit.Package.Version) {
			return fmt.Errorf("invalid nvidia container toolkit package version: %q contains disallowed characters", env.Spec.NVIDIAContainerToolkit.Package.Version)
		}
	}

	// Validate git URLs
	gitURLs := map[string]string{}
	if env.Spec.Kubernetes.Git != nil {
		gitURLs["kubernetes git repo"] = env.Spec.Kubernetes.Git.Repo
	}
	if env.Spec.Kubernetes.Latest != nil {
		gitURLs["kubernetes latest repo"] = env.Spec.Kubernetes.Latest.Repo
	}
	if env.Spec.NVIDIAContainerToolkit.Git != nil {
		gitURLs["nvidia container toolkit git repo"] = env.Spec.NVIDIAContainerToolkit.Git.Repo
	}
	if env.Spec.NVIDIAContainerToolkit.Latest != nil {
		gitURLs["nvidia container toolkit latest repo"] = env.Spec.NVIDIAContainerToolkit.Latest.Repo
	}

	for name, value := range gitURLs {
		if value != "" && !gitURLPattern.MatchString(value) {
			return fmt.Errorf("invalid %s: %q contains disallowed characters", name, value)
		}
	}

	// Validate git refs
	gitRefs := map[string]string{}
	if env.Spec.Kubernetes.Git != nil {
		gitRefs["kubernetes git ref"] = env.Spec.Kubernetes.Git.Ref
	}
	if env.Spec.NVIDIAContainerToolkit.Git != nil {
		gitRefs["nvidia container toolkit git ref"] = env.Spec.NVIDIAContainerToolkit.Git.Ref
	}

	for name, value := range gitRefs {
		if value != "" && !gitRefPattern.MatchString(value) {
			return fmt.Errorf("invalid %s: %q contains disallowed characters", name, value)
		}
	}

	// Validate file paths
	filePaths := map[string]string{
		"private key path": env.Spec.PrivateKey,
		"public key path":  env.Spec.PublicKey,
		"kubeconfig path":  env.Spec.Kubernetes.KubeConfig,
		"kind config path": env.Spec.Kubernetes.KindConfig,
		"kubeadm config":   env.Spec.Kubernetes.KubeAdmConfig,
	}

	for name, value := range filePaths {
		if value != "" && !filePathPattern.MatchString(value) {
			return fmt.Errorf("invalid %s: %q contains disallowed characters", name, value)
		}
	}

	return nil
}
